# configs/config.yaml
server:
  api:
    port: 8080
    host: "0.0.0.0"
    mode: "release"
    base_url: "http://localhost:8080"
  redirect:
    port: 8081
    host: "0.0.0.0"
    mode: "release"

database:
  mysql:
    dsn: "appuser:apppass@tcp(mysql:3306)/short_url?charset=utf8mb4&parseTime=True&loc=Local"
    max_idle_conns: 10
    max_open_conns: 100
    conn_max_lifetime: 3600

redis:
  addr: "redis:6379"
  password: ""
  db: 0
  pool_size: 20
  min_idle_conns: 5

id_generator:
  type: "snowflake"
  snowflake:
    node_id: 1

cache:
  ttl: 3600
  prefix: "shorten_url:"

log:
  level: "info"
  encoding: "json"
  output_paths:
    - "stdout"
    - "logs/app.log"
  error_output_paths:
    - "stderr"
    - "logs/error.log"