# configs/config.dev.yaml
server:
  api:
    port: 8080
    host: "0.0.0.0"
    mode: "debug"
  redirect:
    port: 8081
    host: "0.0.0.0"
    mode: "debug"

database:
  mysql:
    dsn: "appuser:apppass@tcp(localhost:3306)/short_url?charset=utf8mb4&parseTime=True&loc=Local"
    max_idle_conns: 5
    max_open_conns: 20

redis:
  addr: "localhost:6379"
  password: ""
  db: 0

log:
  level: "debug"
  encoding: "console"
  output_paths:
    - "stdout"